//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaSach.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.HoaDon = new HashSet<HoaDon>();
        }
    
        public string maNhanVien { get; set; }
        public bool chucVu { get; set; }
        public string diaChi { get; set; }
        public bool gioiTinh { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public string soDienThoai { get; set; }
        public string tenNhanVien { get; set; }
        public bool trangThaiLamViec { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDon { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
